# Generated by Django 4.2.21 on 2025-08-06 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alias_name', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('type', models.CharField(choices=[('NUCLEAR_GUAGE', 'By nuclear guage methods'), ('SOIL_COMPACTION', 'Compaction characteristic of soil'), ('SIEVE', 'Gradation of Soils Using Sieve'), ('SOIL_INDEX', 'Limits and plasticity index of soil'), ('PROCEDURAL', 'Procedural'), ('SAMPLING', 'Sampling of concrete specimens'), ('CEMENT_CONCRETE', 'Slump and temp of mixed hydraulic cemnet concrete')], max_length=50)),
                ('price', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Text', 'Text'), ('Numberic', 'Numberic'), ('List', 'List')], max_length=50)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('spec_limits', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('optional', models.BooleanField(default=False)),
                ('calculated', models.BooleanField(default=False)),
                ('minimum', models.FloatField(blank=True, null=True)),
                ('maximum', models.FloatField(blank=True, null=True)),
                ('rounding', models.IntegerField(blank=True, null=True)),
                ('decimal_places', models.IntegerField(blank=True, null=True)),
                ('listname', models.CharField(blank=True, choices=[('RAMMER', 'Type of rammer used'), ('MOLD', 'Size of mold'), ('EQUIPMENT', 'Equipment'), ('LIMIT_TESTS', 'Limit Tests'), ('METHOD', 'Method'), ('PROCEDURE', 'Procedure used'), ('DISPERSON_AGENT', 'Disperson agent'), ('SAMPLE_PREPARATION', 'Sample Preparation'), ('TEST_METHOD', 'Test Method')], max_length=50, null=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='app.analysis')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='analysis_attachments/')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='app.analysis')),
            ],
        ),
        migrations.AddField(
            model_name='analysis',
            name='test_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.testmethod'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='user_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.usergroup'),
        ),
    ]
