# Generated by Django 4.2.21 on 2025-09-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='rounding',
            field=models.IntegerField(blank=True, choices=[(1, 'Decimal Places W/0.5 Up'), (2, 'Decimal Places W/0.5 Odd Up')], null=True),
        ),
    ]
