# Generated by Django 4.2.21 on 2025-09-08 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_component_rounding'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentFunctionParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('parameter', models.CharField(max_length=255)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='function_parameters', to='app.component')),
                ('mapped_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_functions', to='app.component')),
            ],
            options={
                'unique_together': {('component', 'parameter')},
            },
        ),
    ]
