# Generated by Django 4.2.21 on 2025-08-08 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_analysistype_alter_analysis_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='user',
            name='idle_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='type',
            field=models.CharField(choices=[('Text', 'Text'), ('Numeric', 'Numeric'), ('List', 'List')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='Unknown User', max_length=255, verbose_name='Full Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='Unknown User', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
