# Generated by Django 4.2.21 on 2025-09-12 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_failed_login_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisattachment',
            name='analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='app.analysis'),
        ),
    ]
