# Generated by Django 4.2.21 on 2025-09-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_analysisattachment_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentresult',
            name='authorization_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='componentresult',
            name='authorization_remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
