# Generated by Django 4.2.21 on 2025-08-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_analysis_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('variables', models.CharField(max_length=255)),
                ('script', models.TextField()),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
