# Generated by Django 4.2.21 on 2025-09-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_componentresult_authorization_flag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestform',
            name='sample_form',
        ),
        migrations.AddField(
            model_name='requestform',
            name='sample_form',
            field=models.ManyToManyField(related_name='request_forms', to='app.sampleform'),
        ),
    ]
