# Generated by Django 4.2.21 on 2025-09-19 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_requestform_sample_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicrequestattachment',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.requestfield'),
        ),
    ]
