# Generated by Django 4.2.21 on 2025-08-09 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_instrument_instrumenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumenthistory',
            name='action_type',
            field=models.CharField(choices=[('Calibrated', 'Calibrated'), ('Prevention', 'Prevention')], max_length=100),
        ),
    ]
