# Generated by Django 4.2.21 on 2025-08-09 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_inventory_inventorytype_unit_stock_inventory_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('analyses_list', 'Analyses List'), ('sample_form_field', 'Sample Form Field'), ('component', 'Component'), ('request_form_field', 'Request Form Field'), ('mail_list', 'Mail List')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usergroup')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='app.list')),
            ],
        ),
    ]
