# Generated by Django 4.2.21 on 2025-09-19 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_dynamicrequestattachment_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicformattachment',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='app.dynamicformentry'),
        ),
    ]
