# Generated by Django 4.2.21 on 2025-08-09 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_list_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_name', models.CharField(max_length=255)),
                ('version', models.IntegerField(default=1)),
                ('group_analysis_list', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('user_groups', models.ManyToManyField(related_name='sample_forms', to='app.usergroup')),
            ],
        ),
        migrations.CreateModel(
            name='SampleField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('field_property', models.CharField(choices=[('text', 'Text'), ('numeric', 'Numeric'), ('date_time', 'Date & Time'), ('list', 'List'), ('link_to_table', 'Link to Table'), ('attachment', 'Attachment')], max_length=50)),
                ('link_to_table', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(default=0)),
                ('list_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.list')),
                ('sample_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='app.sampleform')),
            ],
        ),
    ]
