# Generated by Django 4.2.21 on 2025-09-19 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_dynamicformattachment_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicformattachment',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.samplefield'),
        ),
    ]
