# Generated by Django 4.2.21 on 2025-09-21 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_dynamicformattachment_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='app.analysis'),
        ),
    ]
