# Generated by Django 4.2.21 on 2025-09-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_component_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicformentry',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
