# Generated by Django 4.2.21 on 2025-08-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_dynamicformentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplefield',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
