# Generated by Django 4.2.21 on 2025-08-10 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_samplefield_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RequestForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_name', models.CharField(max_length=255)),
                ('version', models.IntegerField(default=1)),
                ('request_type', models.CharField(choices=[('urgent', 'Urgent'), ('normal', 'Normal'), ('internal', 'Internal'), ('external', 'External')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='app.customer')),
                ('sample_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_forms', to='app.sampleform')),
                ('user_groups', models.ManyToManyField(related_name='request_forms', to='app.usergroup')),
            ],
        ),
        migrations.CreateModel(
            name='RequestField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('field_property', models.CharField(choices=[('text', 'Text'), ('numeric', 'Numeric'), ('date_time', 'Date & Time'), ('list', 'List'), ('link_to_table', 'Link to Table'), ('attachment', 'Attachment')], max_length=50)),
                ('link_to_table', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(default=0)),
                ('required', models.BooleanField(default=False)),
                ('list_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.list')),
                ('request_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='app.requestform')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicRequestEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.requestform')),
            ],
        ),
    ]
