# Generated by Django 4.2.21 on 2025-10-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_dynamicformentry_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicformentry',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('received', 'Received'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('assign_analyst', 'Assign Analyst'), ('authorized', 'Authorized'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('restored', 'Restored')], default='initiated', max_length=20),
        ),
        migrations.AlterField(
            model_name='dynamicrequestentry',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('received', 'Received'), ('authorized', 'Authorized'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('restored', 'Restored')], default='initiated', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='idle_time',
            field=models.PositiveIntegerField(default=15, help_text='Auto logout time in minutes after inactivity'),
        ),
    ]
