# Generated by Django 4.2.21 on 2025-08-12 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_customer_requestform_requestfield_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testmethod',
            options={},
        ),
        migrations.RemoveField(
            model_name='testmethod',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='testmethod',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='testmethod',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='testmethod',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testmethod',
            name='user_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='test_methods', to='app.usergroup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testmethod',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
