# Generated by Django 5.2.7 on 2025-11-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_reporttemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('html_content', models.TextField()),
                ('css_content', models.TextField(blank=True, null=True)),
                ('fields', models.JSONField(default=list)),
                ('sql_query', models.TextField(blank=True, null=True)),
                ('parameters', models.JSONField(blank=True, default=dict, null=True)),
                ('output_format', models.CharField(choices=[('pdf', 'PDF'), ('html', 'HTML')], default='pdf', max_length=10)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
