# Generated by Django 5.2.7 on 2025-11-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_queryreporttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicrequestentry',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
