# Generated by Django 5.2.7 on 2025-12-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_dynamicrequestentry_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='changes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
