# Generated by Django 4.2.21 on 2025-08-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_role_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='user_group',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='user_group',
        ),
        migrations.RemoveField(
            model_name='list',
            name='user_group',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user_group',
        ),
        migrations.RemoveField(
            model_name='testmethod',
            name='user_group',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='user_group',
        ),
        migrations.AddField(
            model_name='analysis',
            name='user_groups',
            field=models.ManyToManyField(blank=True, null=True, to='app.usergroup'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='user_groups',
            field=models.ManyToManyField(blank=True, null=True, to='app.usergroup'),
        ),
        migrations.AddField(
            model_name='list',
            name='user_groups',
            field=models.ManyToManyField(blank=True, to='app.usergroup'),
        ),
        migrations.AddField(
            model_name='product',
            name='user_groups',
            field=models.ManyToManyField(blank=True, null=True, to='app.usergroup'),
        ),
        migrations.AddField(
            model_name='testmethod',
            name='user_groups',
            field=models.ManyToManyField(blank=True, related_name='test_methods', to='app.usergroup'),
        ),
        migrations.AddField(
            model_name='unit',
            name='user_groups',
            field=models.ManyToManyField(blank=True, related_name='units', to='app.usergroup'),
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='user_groups',
        ),
        migrations.AlterField(
            model_name='sampleform',
            name='user_groups',
            field=models.ManyToManyField(blank=True, related_name='sample_forms', to='app.usergroup'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='user_groups',
            field=models.ManyToManyField(blank=True, null=True, related_name='instruments_as_user_group', to='app.usergroup'),
        ),
    ]
