# Generated by Django 4.2.21 on 2025-08-19 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_analysis_user_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicformentry',
            name='analyst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyzed_samples', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dynamicformentry',
            name='logged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_samples', to=settings.AUTH_USER_MODEL),
        ),
    ]
