# Generated by Django 4.2.21 on 2025-08-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_dynamicformentry_analyst_dynamicformentry_logged_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicformentry',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('received', 'Received'), ('completed', 'Completed'), ('authorized', 'Authorized'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('restored', 'Restored')], default='initiated', max_length=20),
        ),
    ]
