# Generated by Django 4.2.21 on 2025-08-19 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_dynamicformentry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicrequestentry',
            name='analyst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyzed_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dynamicrequestentry',
            name='logged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dynamicrequestentry',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('received', 'Received'), ('completed', 'Completed'), ('authorized', 'Authorized'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('restored', 'Restored')], default='initiated', max_length=20),
        ),
    ]
