# Generated by Django 5.2.7 on 2025-12-12 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_user_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('minimum', models.FloatField(blank=True, null=True)),
                ('maximum', models.FloatField(blank=True, null=True)),
                ('decimal_places', models.IntegerField(blank=True, null=True)),
                ('rounding', models.IntegerField(blank=True, null=True)),
                ('spec_limits', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('optional', models.BooleanField(null=True)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample_overrides', to='app.component')),
                ('entry_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_components', to='app.dynamicformentryanalysis')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.unit')),
            ],
        ),
    ]
