# Generated by Django 4.2.21 on 2025-08-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_dynamicrequestentry_analyst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicformentry',
            name='analyses',
            field=models.ManyToManyField(blank=True, related_name='entries', to='app.analysis'),
        ),
    ]
