# Generated by Django 5.2.7 on 2025-12-13 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_samplecomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplecomponent',
            name='calculated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='samplecomponent',
            name='custom_function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.customfunction'),
        ),
        migrations.CreateModel(
            name='SampleComponentFunctionParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=255)),
                ('mapped_sample_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_calculations', to='app.samplecomponent')),
                ('sample_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='function_parameters', to='app.samplecomponent')),
            ],
        ),
    ]
