# Generated by Django 5.2.7 on 2025-12-13 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_samplecomponent_calculated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentresult',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='app.samplecomponent'),
        ),
    ]
