# Generated by Django 4.2.21 on 2025-08-26 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_dynamicformentry_analyses'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='custom_function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='app.customfunction'),
        ),
    ]
