# Generated by Django 5.2.7 on 2025-12-13 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_componentresult_component'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componentresult',
            old_name='component',
            new_name='sample_component',
        ),
    ]
