# Generated by Django 4.2.21 on 2025-08-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_component_custom_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicrequestentry',
            name='analyses',
            field=models.ManyToManyField(blank=True, related_name='requests_entries', to='app.analysis'),
        ),
    ]
