# Generated by Django 4.2.21 on 2025-08-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_dynamicrequestentry_analyses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfunction',
            name='variables',
            field=models.JSONField(),
        ),
    ]
