# Generated by Django 5.2.7 on 2025-12-14 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_rename_component_componentresult_sample_component'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='componentresult',
            unique_together={('entry', 'sample_component')},
        ),
    ]
