# Generated by Django 4.2.21 on 2025-08-31 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_customfunction_variables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumenthistory',
            name='action_type',
            field=models.CharField(choices=[('Calibration', 'Calibration'), ('Prevention', 'Prevention')], max_length=100),
        ),
        migrations.RemoveField(
            model_name='sampleform',
            name='group_analysis_list',
        ),
        migrations.AddField(
            model_name='sampleform',
            name='group_analysis_list',
            field=models.ManyToManyField(blank=True, related_name='sample_forms', to='app.analysis'),
        ),
    ]
