# Generated by Django 5.2.7 on 2025-12-14 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_componentresult_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='componentresult',
            unique_together=set(),
        ),
    ]
