# Generated by Django 5.2.7 on 2025-12-17 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_componentresult_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicformentryanalysis',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.dynamicformentry'),
        ),
    ]
