# Generated by Django 4.2.21 on 2025-09-02 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_instrumenthistory_action_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicFormAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='app.dynamicformentry')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.samplefield')),
            ],
        ),
    ]
