# Generated by Django 5.2.7 on 2025-12-17 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_dynamicformentryanalysis_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplecomponent',
            name='entry_analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample_components', to='app.dynamicformentryanalysis'),
        ),
    ]
