# Generated by Django 4.2.21 on 2025-09-02 09:51

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_dynamicformattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicformattachment',
            name='file',
            field=models.FileField(upload_to=app.models.attachment_upload_path),
        ),
    ]
