# Generated by Django 5.2.7 on 2025-12-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_samplecomponent_entry_analysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productanalysis',
            name='components',
        ),
        migrations.AddField(
            model_name='productanalysis',
            name='sample_components',
            field=models.ManyToManyField(blank=True, to='app.samplecomponent'),
        ),
    ]
