# Generated by Django 4.2.21 on 2025-09-02 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_dynamicformattachment_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicRequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/request/')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='app.dynamicrequestentry')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.requestfield')),
            ],
        ),
    ]
