# Generated by Django 5.2.7 on 2026-01-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_remove_productanalysis_components_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicformentry',
            name='secondary_id',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
