# Generated by Django 4.2.21 on 2025-09-07 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_componentresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicFormEntryAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.analysis')),
                ('components', models.ManyToManyField(blank=True, to='app.component')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dynamicformentry')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
