# Generated by Django 5.2.7 on 2026-01-09 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_dynamicformentry_secondary_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SamplingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='analyses',
        ),
        migrations.AlterField(
            model_name='product',
            name='user_groups',
            field=models.ManyToManyField(blank=True, related_name='products', to='app.usergroup'),
        ),
        migrations.CreateModel(
            name='ProductSamplingGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.grade')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sampling_grades', to='app.product')),
                ('sampling_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.samplingpoint')),
            ],
            options={
                'unique_together': {('product', 'sampling_point', 'grade')},
            },
        ),
        migrations.CreateModel(
            name='ProductSamplingGradeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.analysis')),
                ('product_sampling_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='app.productsamplinggrade')),
                ('sample_components', models.ManyToManyField(blank=True, related_name='product_sampling_grade_analyses', to='app.samplecomponent')),
            ],
            options={
                'unique_together': {('product_sampling_grade', 'analysis')},
            },
        ),
        migrations.DeleteModel(
            name='ProductAnalysis',
        ),
    ]
