# Generated by Django 5.2.7 on 2026-02-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_grade_samplingpoint_remove_product_analyses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplecomponent',
            name='type',
            field=models.CharField(blank=True, choices=[('Text', 'Text'), ('Numeric', 'Numeric'), ('List', 'List')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dynamicformentry',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('received', 'Received'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('assign_analyst', 'Assign Analyst'), ('hold', 'Hold'), ('unhold', 'Un Hold'), ('authorized', 'Authorized'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('reactivate', 'Reactivate')], default='initiated', max_length=20),
        ),
    ]
