# Generated by Django 4.2.21 on 2026-02-14 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_samplecomponent_type_alter_dynamicformentry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('view', 'View'), ('update', 'Update'), ('delete', 'Delete'), ('receive', 'Receive'), ('result_entry', 'Result Entry'), ('authorize', 'Authorize'), ('cancel_restore', 'Cancel/Restore'), ('reactivate', 'Reactivate')], max_length=100),
        ),
        migrations.AlterField(
            model_name='productsamplinggrade',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.grade'),
        ),
        migrations.AlterField(
            model_name='productsamplinggrade',
            name='sampling_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.samplingpoint'),
        ),
    ]
