# Generated by Django 4.2.21 on 2026-02-15 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_permission_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='test_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.testmethod'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='version',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
