# Generated by Django 4.2.21 on 2026-02-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_analysis_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='batch_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
