# Generated by Django 4.2.21 on 2026-02-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_inventory_batch_no_inventory_supplier_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='statushistory',
            name='tat',
            field=models.DurationField(blank=True, help_text='Time difference from previous status change', null=True),
        ),
    ]
