# Generated by Django 4.2.21 on 2026-02-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_statushistory_tat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statushistory',
            name='tat',
            field=models.FloatField(blank=True, help_text='TAT in seconds', null=True),
        ),
    ]
