# Generated by Django 4.2.21 on 2026-02-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_statushistory_tat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queryreporttemplate',
            old_name='html_content',
            new_name='raw_html_content',
        ),
        migrations.AddField(
            model_name='queryreporttemplate',
            name='jinja_html_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='tat',
            field=models.FloatField(blank=True, help_text='TAT in seconds', null=True),
        ),
    ]
