# Generated by Django 4.2.21 on 2026-02-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_rename_html_content_queryreporttemplate_raw_html_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('FG_SAMPLE', 'FG Sample'), ('BLEND_SAMPLE', 'Blend Sample'), ('RM_SAMPLE', 'RM Sample'), ('PM_SAMPLE', 'PM Sample')], default='FG_SAMPLE', max_length=20),
        ),
    ]
