# Generated by Django 4.2.21 on 2026-02-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('FINISHED_GOODS', 'Finished Goods'), ('BLEND', 'Blend'), ('RAW_MATERIALS', 'Raw Materials'), ('PACKAGING_MATERIALS', 'Packaging Materials'), ('FLAVOUR_MATERIALS', 'Flavour Materials')], default='FG_SAMPLE', max_length=20),
        ),
    ]
