# Generated by Django 4.2.21 on 2026-02-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_alter_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicformentry',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('received', 'Received'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('assign_analyst', 'Assign Analyst'), ('hold', 'Hold'), ('unhold', 'Un Hold'), ('release', 'Realease'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('reactivate', 'Reactivate')], default='initiated', max_length=20),
        ),
        migrations.AlterField(
            model_name='dynamicrequestentry',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('received', 'Received'), ('release', 'Realease'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('restored', 'Restored')], default='initiated', max_length=20),
        ),
        migrations.AlterField(
            model_name='permission',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('view', 'View'), ('update', 'Update'), ('delete', 'Delete'), ('receive', 'Receive'), ('result_entry', 'Result Entry'), ('release', 'Realease'), ('cancel_restore', 'Cancel/Restore'), ('reactivate', 'Reactivate')], max_length=100),
        ),
    ]
