# Generated by Django 4.2.21 on 2026-02-28 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_generatedreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedreport',
            name='template',
            field=models.ForeignKey(default=32, on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='app.queryreporttemplate'),
            preserve_default=False,
        ),
    ]
