# Generated by Django 4.2.21 on 2026-02-28 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_generatedreport_template'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dynamicformentry',
            old_name='secondary_id',
            new_name='sample_text_id',
        ),
    ]
