# Generated by Django 4.2.21 on 2026-03-04 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_statushistory_tat'),
        ('app', '0046_rename_secondary_id_dynamicformentry_sample_text_id'),
    ]

    operations = [
    ]
