# Generated by Django 4.2.21 on 2026-03-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_rename_secondary_id_dynamicformentry_sample_text_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicformentry',
            name='user_groups',
            field=models.ManyToManyField(blank=True, related_name='sample_entries', to='app.usergroup'),
        ),
    ]
