# Generated by Django 4.2.21 on 2026-03-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_dynamicformentry_user_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedreport',
            name='id',
            field=models.CharField(editable=False, max_length=30, primary_key=True, serialize=False),
        ),
    ]
