# Generated by Django 4.2.21 on 2026-03-05 17:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_alter_generatedreport_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='statushistory',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rejection_reason', models.TextField()),
                ('corrective_actions', models.TextField(blank=True, null=True)),
                ('preventive_actions', models.TextField(blank=True, null=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='app.dynamicformentry')),
            ],
        ),
    ]
