# Generated by Django 4.2.21 on 2026-03-09 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='app.unit'),
        ),
    ]
