# Generated by Django 4.2.21 on 2026-03-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_statushistory_reason_investigation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicformentry',
            name='retaining_sample_location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
