# Generated by Django 4.2.21 on 2026-03-06 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_dynamicformentry_retaining_sample_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('consumed_quantity', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='app.stock')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
