# Generated by Django 4.2.21 on 2026-03-09 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_stockconsumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicformentry',
            name='is_followup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dynamicformentry',
            name='parent_sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_samples', to='app.dynamicformentry'),
        ),
    ]
