# Generated by Django 4.2.21 on 2026-03-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_dynamicformentry_is_followup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='batch_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
