# Generated by Django 4.2.21 on 2026-03-10 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_nicotineassayreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='nicotine_assay_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='app.nicotineassayreport'),
        ),
    ]
