# Generated by Django 4.2.21 on 2026-03-10 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_analysis_nicotine_assay_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis',
            old_name='nicotine_assay_report',
            new_name='prep',
        ),
    ]
