# Generated by Django 4.2.21 on 2026-03-16 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_component_default_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockconsumption',
            name='consumed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
