# Generated by Django 4.2.21 on 2026-03-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_stockconsumption_consumed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('view', 'View'), ('update', 'Update'), ('delete', 'Delete'), ('receive', 'Receive'), ('result_entry', 'Result Entry'), ('release', 'Realease'), ('cancel_restore', 'Cancel/Restore'), ('reactivate', 'Reactivate'), ('consume_stock', 'Consume Stock')], max_length=100),
        ),
    ]
