# Generated by Django 4.2.21 on 2026-03-31 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_rename_blend_weight_mg_nicotineassayreport_ammonium_acetate_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nicotineassayreport',
            name='prep_sub_type',
            field=models.CharField(blank=True, choices=[('NSS', 'Nicotine Standard Solution'), ('PSS', 'Solvent Solution')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='nicotineassayreport',
            name='prep_type',
            field=models.CharField(choices=[('MPA', 'Phase A'), ('MPB', 'Phase B'), ('MPC', 'Phase C'), ('MPS', 'Solvent and Solution')], max_length=3),
        ),
    ]
