# Generated by Django 4.2.21 on 2026-03-31 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_nicotineassayreport_prep_sub_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nicotineassayreport',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
