# Generated by Django 4.2.21 on 2026-04-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_training_usertraining_training_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='attachment',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='training_id',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
