# Generated by Django 4.2.21 on 2026-04-07 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_remove_nicotineassayreport_prepared_by_preparation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='prep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='app.preparation'),
        ),
    ]
