# Generated by Django 4.2.21 on 2026-04-11 16:49

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_alter_analysis_prep'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingMaterialSampleInspection',
            fields=[
                ('inspection_sheet_no', models.CharField(default=app.models.generate_inspection_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('grn_number', models.CharField(blank=True, max_length=100, null=True)),
                ('received_total_number', models.PositiveIntegerField(blank=True, null=True)),
                ('vendor_lot_number', models.CharField(blank=True, max_length=100, null=True)),
                ('clarity', models.CharField(blank=True, choices=[('clear', 'Clear'), ('not_clear', 'Not Clear')], max_length=20, null=True)),
                ('item_description', models.CharField(blank=True, choices=[('present', 'Present'), ('absent', 'Absent')], max_length=20, null=True)),
                ('supplier_name', models.CharField(blank=True, choices=[('present', 'Present'), ('absent', 'Absent')], max_length=20, null=True)),
                ('supplier_lot_number', models.CharField(blank=True, choices=[('present', 'Present'), ('absent', 'Absent')], max_length=20, null=True)),
                ('manufacturing_date', models.CharField(blank=True, choices=[('present', 'Present'), ('absent', 'Absent')], max_length=20, null=True)),
                ('expiry_date', models.CharField(blank=True, choices=[('present', 'Present'), ('absent', 'Absent')], max_length=20, null=True)),
                ('number_of_containers_to_be_opened', models.PositiveIntegerField(blank=True, null=True)),
                ('sampled_quantity', models.CharField(blank=True, max_length=255, null=True)),
                ('sampled_by', models.CharField(blank=True, max_length=255, null=True)),
                ('container_sealed_after_sampling', models.BooleanField(default=False)),
                ('container_labeled_after_sealed', models.BooleanField(default=False)),
                ('checked_by', models.CharField(blank=True, max_length=255, null=True)),
                ('checked_sign_date', models.DateField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_sign_date', models.DateField(blank=True, null=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='app.product')),
            ],
            options={
                'db_table': 'incoming_material_sample_inspection',
                'ordering': ['-created_at'],
            },
        ),
    ]
