# Generated by Django 4.2.21 on 2026-04-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_incomingmaterialsampleinspection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='prep',
        ),
        migrations.AddField(
            model_name='analysis',
            name='prep',
            field=models.ManyToManyField(blank=True, related_name='analyses', to='app.preparation'),
        ),
    ]
