# Generated by Django 4.2.21 on 2026-04-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_remove_analysis_prep_analysis_prep'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparation',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
