# Generated by Django 4.2.21 on 2026-04-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_preparation_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomingmaterialsampleinspection',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='incomingmaterialsampleinspection',
            name='accepted_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incomingmaterialsampleinspection',
            name='decision',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('partial', 'Partially Accepted')], max_length=20, null=True),
        ),
    ]
