# Generated by Django 4.2.21 on 2026-04-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_remove_incomingmaterialsampleinspection_is_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplefield',
            name='field_property',
            field=models.CharField(choices=[('text', 'Text'), ('numeric', 'Numeric'), ('date', 'Date'), ('list', 'List'), ('link_to_table', 'Link to Table'), ('attachment', 'Attachment')], max_length=50),
        ),
    ]
