# Generated by Django 4.2.21 on 2026-05-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_alter_samplefield_field_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='instruments',
            field=models.ManyToManyField(blank=True, related_name='analyses', to='app.instrument'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='status',
            field=models.CharField(choices=[('in_service', 'In Service'), ('out_of_service', 'Out of Service')], default='in_service', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
