# Generated by Django 4.2.21 on 2026-05-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_analysis_instruments_instrument_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='document_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
