# Generated by Django 4.2.21 on 2026-05-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_product_document_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nicotineassayreport',
            name='prep_sub_type',
        ),
        migrations.AlterField(
            model_name='nicotineassayreport',
            name='prep_type',
            field=models.CharField(choices=[('MPA', 'Phase A'), ('MPB', 'Phase B'), ('MPC', 'Phase C'), ('PSS', 'Solvent Solution'), ('NSS', 'Nicotine Standard')], max_length=3),
        ),
    ]
