# Generated by Django 4.2.21 on 2026-05-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_remove_nicotineassayreport_prep_sub_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nicotineassayreport',
            name='prep_type',
            field=models.CharField(max_length=10),
        ),
    ]
