# Generated by Django 4.2.21 on 2026-05-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0075_alter_nicotineassayreport_prep_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmethod',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='test_methods/'),
        ),
    ]
