# Generated by Django 4.2.21 on 2026-05-12 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_preparationattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preparationattachment',
            name='preparation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='app.preparation'),
        ),
    ]
