# Generated by Django 4.2.21 on 2026-05-12 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0078_alter_preparationattachment_preparation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preparationattachment',
            name='url',
        ),
    ]
