# Generated by Django 4.2.21 on 2026-05-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0079_remove_preparationattachment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingmaterialsampleinspection',
            name='coa',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('missing', 'Missing')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='incomingmaterialsampleinspection',
            name='container_sealing_closure',
            field=models.CharField(blank=True, choices=[('good', 'Good'), ('damaged', 'Damaged')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='incomingmaterialsampleinspection',
            name='high_risk_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incomingmaterialsampleinspection',
            name='leakage_contamination',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('observed', 'Observed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='incomingmaterialsampleinspection',
            name='material_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='incomingmaterialsampleinspection',
            name='material_visual_appearance',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('abnormal', 'Abnormal')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='incomingmaterialsampleinspection',
            name='msds_sds',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('missing', 'Missing')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='incomingmaterialsampleinspection',
            name='no_of_cartons_to_be_opened',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incomingmaterialsampleinspection',
            name='outer_packaging_condition',
            field=models.CharField(blank=True, choices=[('good', 'Good'), ('damaged', 'Damaged')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='incomingmaterialsampleinspection',
            name='retain_sample_quantity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incomingmaterialsampleinspection',
            name='sampling_level_applied',
            field=models.CharField(blank=True, choices=[('pallet', 'Pallet'), ('carton', 'Carton'), ('unit', 'Unit'), ('n', 'N')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='incomingmaterialsampleinspection',
            name='sampling_type',
            field=models.CharField(blank=True, choices=[('high_risk', 'High Risk'), ('low_risk', 'Low Risk')], max_length=20, null=True),
        ),
    ]
