# Generated by Django 4.2.21 on 2026-05-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0080_incomingmaterialsampleinspection_coa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlendReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=100)),
                ('parameter_name', models.CharField(max_length=100)),
                ('result', models.FloatField()),
                ('date', models.DateTimeField()),
                ('instrument_name', models.CharField(max_length=100)),
            ],
        ),
    ]
