# Generated by Django 4.2.21 on 2026-05-19 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0081_blendreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicformentry',
            name='inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='app.incomingmaterialsampleinspection'),
        ),
    ]
