# Generated by Django 4.2.21 on 2026-06-04 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0083_user_two_factor_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blendreport',
            old_name='parameter_name',
            new_name='compound_name',
        ),
        migrations.RenameField(
            model_name='blendreport',
            old_name='sample_id',
            new_name='result_set_id',
        ),
        migrations.RemoveField(
            model_name='blendreport',
            name='date',
        ),
        migrations.RemoveField(
            model_name='blendreport',
            name='result',
        ),
        migrations.AddField(
            model_name='blendreport',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blendreport',
            name='approved_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blendreport',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blendreport',
            name='authored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blendreport',
            name='authored_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blendreport',
            name='blend_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blendreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blendreport',
            name='sample_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blendreport',
            name='sample_set_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blendreport',
            name='sample_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blendreport',
            name='sku_strength',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blendreport',
            name='time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blendreport',
            name='instrument_name',
            field=models.CharField(default='Blend Report', max_length=100),
        ),
    ]
