# Generated by Django 4.2.21 on 2026-06-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0084_rename_parameter_name_blendreport_compound_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='acceptance_criteria',
            field=models.CharField(blank=True, help_text='Acceptance criteria for this component', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='samplecomponent',
            name='acceptance_criteria',
            field=models.CharField(blank=True, help_text='Acceptance criteria for this component', max_length=255, null=True),
        ),
    ]
