# Generated by Django 4.2.21 on 2026-06-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0085_component_acceptance_criteria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='two_factor_enabled',
            new_name='is_2fa_enabled',
        ),
        migrations.AddField(
            model_name='user',
            name='twofa_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
