# Generated by Django 4.2.21 on 2026-06-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0086_rename_two_factor_enabled_user_is_2fa_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='erp_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
