# Generated by Django 4.2.21 on 2026-06-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0087_product_erp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='erp_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
