# Generated by Django 6.0.6 on 2026-07-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0089_alter_product_document_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(db_index=True, max_length=100)),
                ('sample_name', models.CharField(max_length=255)),
                ('analysis_name', models.CharField(max_length=255)),
                ('result', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BlendReport',
        ),
    ]
