# Generated by Django 6.0.6 on 2026-07-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0091_sampleanalysisresult_reviewed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingmaterialsampleinspection',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
    ]
