# Generated by Django 6.0.6 on 2026-07-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0092_incomingmaterialsampleinspection_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingmaterialsampleinspection',
            name='generated_report_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
