# Generated by Django 6.0.6 on 2026-07-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0093_incomingmaterialsampleinspection_generated_report_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sampleanalysisresult',
            old_name='sample_name',
            new_name='product_name',
        ),
        migrations.RemoveField(
            model_name='sampleanalysisresult',
            name='reviewed_by',
        ),
        migrations.AddField(
            model_name='sampleanalysisresult',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sampleanalysisresult',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
