# Generated by Django 6.0.6 on 2026-07-22 10:29

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0094_rename_sample_name_sampleanalysisresult_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingmaterialsampleinspection',
            name='sampling_level_applied',
            field=models.JSONField(blank=True, default=list, validators=[app.models.validate_sampling_levels]),
        ),
    ]
