# Generated by Django 6.0.6 on 2026-07-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0095_alter_incomingmaterialsampleinspection_sampling_level_applied'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamicformentryanalysis',
            options={'ordering': ['display_order']},
        ),
        migrations.AlterModelOptions(
            name='productsamplinggradeanalysis',
            options={'ordering': ['display_order']},
        ),
        migrations.AddField(
            model_name='dynamicformentryanalysis',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productsamplinggradeanalysis',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
