# Generated by Django 6.0.6 on 2026-08-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0096_alter_dynamicformentryanalysis_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingmaterialsampleinspection',
            name='qc_label_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
