# Generated by Django 6.0.6 on 2026-08-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0097_incomingmaterialsampleinspection_qc_label_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('view', 'View'), ('update', 'Update'), ('delete', 'Delete'), ('receive', 'Receive'), ('result_entry', 'Result Entry'), ('release', 'Realease'), ('cancel_restore', 'Cancel/Restore'), ('reactivate', 'Reactivate'), ('consume_stock', 'Consume Stock'), ('approve', 'Approve')], max_length=100),
        ),
    ]
