# Generated by Django 6.0.6 on 2026-08-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0098_alter_permission_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='trainings',
            field=models.ManyToManyField(blank=True, related_name='analyses', to='app.training'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='user_groups',
            field=models.ManyToManyField(blank=True, to='app.usergroup'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='user_groups',
            field=models.ManyToManyField(blank=True, related_name='instruments_as_user_group', to='app.usergroup'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='user_groups',
            field=models.ManyToManyField(blank=True, to='app.usergroup'),
        ),
        migrations.AlterField(
            model_name='testmethod',
            name='user_groups',
            field=models.ManyToManyField(related_name='test_methods', to='app.usergroup'),
        ),
    ]
