# Generated by Django 6.0.6 on 2026-08-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0099_alter_analysis_trainings_alter_analysis_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sample_quantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
