# Generated by Django 6.0.6 on 2026-08-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0100_product_sample_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingmaterialsampleinspection',
            name='received_total_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
