# Generated by Django 6.0.6 on 2026-10-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0103_alter_permission_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplefield',
            name='unique',
            field=models.BooleanField(default=False),
        ),
    ]
