"""
Django settings for project project.
Generated by 'django-admin startproject' using Django 4.0.2
"""

import os
import certifi
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# ======================
# BASE
# ======================
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = "9w0r4r7y&aokq%s!ftu9r+de*-pchjqw%+ov38e*e$2lvzs3yh"

DEBUG = False if os.environ.get("DEBUG") == "False" else True

ALLOWED_HOSTS = ["*"]

# ======================
# APPLICATIONS
# ======================
INSTALLED_APPS = [
    "corsheaders",
    "whitenoise.runserver_nostatic",

    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # third party
    "rest_framework",
    "django_filters",
    "drf_spectacular",
    "rest_framework.authtoken",
    "crispy_forms",
    "storages",
    "csp",
    "django_celery_beat",

    # project apps
    "app.apps.AppConfig",
]

AUTH_USER_MODEL = "app.User"

# ======================
# MIDDLEWARE
# ======================
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # MUST be first
    "django.middleware.security.SecurityMiddleware",
    'csp.middleware.CSPMiddleware', 
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "app.middleware.CurrentUserMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# ======================
# GLOBAL CORS (DEBUG TRUE / FALSE BOTH)
# ======================
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = False

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "x-role-id",
]

CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS",
]

CSRF_TRUSTED_ORIGINS = [
    "http://*",
    "https://*",
]

CONTENT_SECURITY_POLICY = {
    "DIRECTIVES": {
        "default-src": ("'self'",),

        "script-src": (
            "'self'",
            "'unsafe-inline'",
            "'unsafe-eval'",
        ),

        "style-src": (
            "'self'",
            "'unsafe-inline'",
        ),

        "img-src": (
            "'self'",
            "data:",
            "blob:",
        ),

        "connect-src": (
            "'self'",
            "http://localhost:3000",
            "https://pilims.netlify.app",
        ),

        "font-src": (
            "'self'",
            "data:",
        ),

        "frame-ancestors": ("'none'",),
    }
}

# ======================
# URLS / TEMPLATES
# ======================
ROOT_URLCONF = "project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "template"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.template.context_processors.media",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "project.wsgi.application"

# ======================
# DATABASE
# ======================
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": os.getenv("POSTGRES_DB", "postgres"),
#         "USER": os.getenv("POSTGRES_USER", "postgres"),
#         "PASSWORD": os.getenv("POSTGRES_PASSWORD", "aszx1234"),
#         "HOST": os.getenv("DB_HOST", "db"),
#         "PORT": os.getenv("DB_PORT", "5432"),
#     }
# }

FRONTEND_BASE_URL = os.getenv("FRONTEND_BASE_URL", "https://pilims.netlify.app")

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3", 
    }
}

# ======================
# REST FRAMEWORK
# ======================
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework.authentication.SessionAuthentication",
        "app.authentication.IdleTimeoutTokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    # 'DEFAULT_RENDERER_CLASSES': [
    #     'rest_framework.renderers.JSONRenderer',
    # ]
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Dental AI",
    "DESCRIPTION": "Dental API",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

# ======================
# AUTH
# ======================
AUTHENTICATION_BACKENDS = [
    "app.authentication.EmailBackend",
    "django.contrib.auth.backends.ModelBackend",
]

LOGIN_URL = "/login"

# ======================
# INTERNATIONALIZATION
# ======================
LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Karachi"
USE_I18N = True
USE_TZ = True

# ======================
# STATIC / MEDIA
# ======================
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# ======================
# EMAIL
# ======================
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "dilawaizkhan08@gmail.com")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "biuijrdpktndiiuc")

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# ======================
# SECURITY (PRODUCTION SAFE)
# ======================
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = False  # enable only if HTTPS fully configured

# ======================
# DEFAULTS
# ======================
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# settings.py

ORACLE_CONFIG = {
    "URL": "https://fa-exto-test-saasfaprod1.fa.ocs.oraclecloud.com/xmlpserver/services/PublicReportService",
    "USER": "aps.consultant",
    "PASSWORD": "APS@22334455",
    "REPORT_PATH": "/Custom/Custom Report/Inventory/New Report/BADAEL_INV_BATCH_DETAILS/BADAEL_INV_BATCH_DETAILS_REP.xdo"
}


os.environ["SSL_CERT_FILE"] = certifi.where()


import os
from celery.schedules import crontab

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"
CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/0"

# CELERY_BROKER_URL = "filesystem://"
# CELERY_RESULT_BACKEND = "rpc://" 

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"

CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

CELERY_BROKER_TRANSPORT_OPTIONS = {
    "data_folder_in": os.path.join(BASE_DIR, "blend_report_in"),
    "data_folder_out": os.path.join(BASE_DIR, "blend_report_out"),
    "data_folder_processed": os.path.join(BASE_DIR, "cblend_report_processed"),
}

CELERY_BEAT_SCHEDULE = {
    "blend-report-daily-2am": {
        "task": "app.tasks.process_blend_reports",
        "schedule": crontab(hour=17, minute=59),
    },
}

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     },
# }


