"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 4.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os,certifi
from pathlib import Path

import os
from dotenv import load_dotenv
load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

LICENSE_VALID = False        # by default locked
LICENSE_DATA = None          # no license loaded yet
LICENSE_ERROR = "License not validated"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "9w0r4r7y&aokq%s!ftu9r+de*-pchjqw%+ov38e*e$2lvzs3yh"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False if os.environ.get("DEBUG") == "False" else True

ALLOWED_HOSTS = ["*"]
SSL = False if os.environ.get("SSL") == "False" else True
FRONTEND_URL = os.environ.get("FRONTEND_URL")
BACKEND_URL=os.environ.get("BACKEND_URL")
# print("FRONTEND_URL", FRONTEND_URL)
PASSWORD_RESET_URL = os.environ.get("PASSWORD_RESET_URL")
AUTH_USER_MODEL = "app.User"
DEBUG =  False if os.environ.get("DEBUG") == "False" else True
CORS_ORIGIN_ALLOW_ALL = True
CSRF_TRUSTED_ORIGINS = [os.environ.get("CSRF_TRUSTED_ORIGINS")]

CORS_ALLOW_CREDENTIALS = True
ALLOWED_HOSTS = ["*"]
SSL = False if os.environ.get("SSL") == "False" else True


# LOGIN_URL = "/"
# LOGIN_REDIRECT_URL = "/home/"
# LOGOUT_REDIRECT_URL = "/"

ADMINS = [("Fabtechsol", "workwithfabtechsol@gmail.com"),("Dilawaiz", "dilawaizkhan08@gmail.com")]
SERVER_EMAIL = os.environ.get("EMAIL_HOST_USER")
FRONTEND_SIGNUP_URL = os.environ.get("FRONTEND_SIGNUP_URL")

LOGIN_URL = "/login"
if not DEBUG:
    CSRF_TRUSTED_ORIGINS = [os.environ.get("CSRF_TRUSTED_ORIGINS")]
    CORS_ORIGIN_ALLOW_ALL = True
    CORS_ALLOW_CREDENTIALS = True
    CSRF_COOKIE_DOMAIN = os.environ.get("CSRF_COOKIE_DOMAIN")
if SSL:
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


INSTALLED_APPS = [
    "whitenoise.runserver_nostatic",
    "django.contrib.sitemaps",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]
# Project applications
INSTALLED_APPS += [
    # "app",
    "app.apps.AppConfig", 

]
# Third party applications
INSTALLED_APPS += [
    "rest_framework",
    "django_rest_passwordreset",
    "django_filters",
    "drf_spectacular",
    "rest_framework.authtoken",
    'storages',
    "crispy_forms",
    "corsheaders",
    "slick_reporting",
    # "django_eventstream",
    # "django_grip"
]

# EVENTSTREAM_CHANNELS = {
#     "global": {
#         "broadcast": [
#             "django.db.models.signals.post_save",
#             "django.db.models.signals.post_delete",
#         ],
#     },
# }


# EVENTSTREAM_REDIS = {
#     'host': 'localhost',
#     'port': 6379,
#     'db': 0,
# }



REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework.authentication.SessionAuthentication",
        "app.authentication.IdleTimeoutTokenAuthentication",

    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    # "DEFAULT_PAGINATION_CLASS": "app.pagination.CustomPageNumberPagination",
    # "PAGE_SIZE": 10,
    'DATETIME_FORMAT': "%Y-%m-%d %H:%M:%S",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Dental AI",
    "DESCRIPTION": "Dental API",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}


AUTHENTICATION_BACKENDS = [
    'app.authentication.EmailBackend', 
    'django.contrib.auth.backends.ModelBackend'
]

CRISPY_TEMPLATE_PACK = "uni_form"
# MIDDLEWARE = [
#     "django.middleware.security.SecurityMiddleware",
#     "django.contrib.sessions.middleware.SessionMiddleware",
#     "django.middleware.common.CommonMiddleware",
#     # 'app.middleware.DisableCSRFMiddleware',
#     "django.middleware.csrf.CsrfViewMiddleware",
#     "django.contrib.auth.middleware.AuthenticationMiddleware",
#     "django.contrib.messages.middleware.MessageMiddleware",
#     "django.middleware.clickjacking.XFrameOptionsMiddleware",
#     'corsheaders.middleware.CorsMiddleware',
#     "whitenoise.middleware.WhiteNoiseMiddleware",
#     "app.middleware.CurrentUserMiddleware",
    
# ]


MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "app.middleware.LicenseMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware", 
    "app.middleware.CurrentUserMiddleware", 

    
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # "django_eventstream.middleware.EventStreamMiddleware",

    
]

ROOT_URLCONF = "project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "template"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.template.context_processors.media",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]




WSGI_APPLICATION = "project.wsgi.application"
# ASGI_APPLICATION = "project.asgi.application"
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     },
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'postgres'),
        'USER': os.getenv('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'aszx1234'),
        'HOST': os.getenv('DB_HOST', 'db'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}




# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "en-us"

# TIME_ZONE = "UTC"
TIME_ZONE = 'Asia/Karachi'


USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

print(os.environ.get("DEBUG"))
s3 = True if os.environ.get("DEBUG") == "False" else False
if s3:
    AWS_S3_FILE_OVERWRITE = False
    # AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID")
    # AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY")
    AWS_S3_SIGNATURE_VERSION = "s3v4"
    AWS_STORAGE_BUCKET_NAME = os.environ.get("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_OBJECT_PARAMETERS = {"CacheControl": "max-age=86400",'ACL': 'private',}
    BUCKET_URL = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"
    AWS_S3_CUSTOM_DOMAIN = None 
    # Set the expiration time for signed URLs (e.g., 3600 seconds = 1 hour)
    # AWS_QUERYSTRING_AUTH = True
    AWS_QUERYSTRING_EXPIRE = 3600  # 1 hour expiration
    AWS_S3_REGION_NAME = 'us-east-2'
    # s3 static settings
    STATIC_LOCATION = "static"
    STATIC_URL = f"https://{BUCKET_URL}/{STATIC_LOCATION}/"
    STATICFILES_STORAGE = "project.storage_backends.StaticStorage"

    # s3 public media settings
    PUBLIC_MEDIA_LOCATION = "media"
    MEDIA_URL = f"https://{BUCKET_URL}/{PUBLIC_MEDIA_LOCATION}/"
    DEFAULT_FILE_STORAGE = "project.storage_backends.MediaStorage"

    # s3 private media settings
    PRIVATE_MEDIA_LOCATION = "private"
    PRIVATE_FILE_STORAGE = "project.storage_backends.PrivateStorage"
else:
    print("DEBUG")
    STATIC_URL = "/static/"
    STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

    MEDIA_ROOT = BASE_DIR / "media"
    MEDIA_URL = "/media/"

    FEED_URL = "/feeds/"


STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
FEED_ROOT = os.path.join(BASE_DIR, "feeds")

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


os.environ["SSL_CERT_FILE"] = certifi.where()


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))  # Defaults to 587 if not set
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')  # Gmail address from .env
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')  # App password from .env
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER





